"""INNOVQ -- innovation-space amortized posterior for the VBPM (implements SPEC.md).

The posterior keeps the existing bi-GRU trunk (BarPointerVAE.encode_posterior) and replaces
the absolute-state post_head with
  (i)  an INIT head  [mean_t c_t, c_1] -> t=1 state (WC phase mu/rho1<=rho1_max,
       Student-t level mu/scale, meter logits -- one logit set per crop, redrawn at
       bar crossings, exactly the pm_common convention), and
  (ii) an INNOVATION head [c_t, z_feat(z_{t-1})] -> bounded per-frame nudges
       mu_eps^phi = tanh(.)*s_phi, rho_q = 1-softplus(.+R0) (init at rho_p),
       mu_eps^lt  = tanh(.)*s_lt,  s_lv = softplus(.+B0)+1e-5 (init at sigma_dlt).
q's trajectory is generated by the PRIOR's own recursion plus the nudges:
    phi_t = wrap(phi_{t-1} + exp(lt_{t-1}) + eps^phi_t),   lt_t = level_t + dev_t,
    level_t = level_{t-1} + eps^lt_t,                      dev_t ~ N(0, 1e-3) = prior (KL 0)
so the per-step phase KL reduces exactly to KL(WC(mu_eps,rho_q) || WC(0,rho_p)) --
sample-path independent, computed in the numerically-stable innovation form (float64,
cancellation-free via sq = 1-rho_q = softplus output). ELBO = plain single-sample SGVB,
physical prior, beta arg. Full BPTT, no detach inside the recursion; WC reparam u-clamped.

Faithfulness: same family (amortized, WC/Student-t/Cat per coordinate), beta=1 at
convergence, no free-bits, no pos_weight, placement supervision ends before handover.
Machinery reused read-only: pm_common (crops, recon, kl_t_mc, PHYS), m2_targets (PF
teacher), vbpm.distributions / vbpm.evaluate. Protocol mirrors m2_distill.py.
"""
import argparse, json, math, sys, time
import numpy as np, torch, torch.nn as nn, torch.nn.functional as F

sys.path.insert(0, "/home/sogang/jaehoon/VBPM_reintegration")
sys.path.insert(0, "/home/sogang/jaehoon/VBPM_reintegration/vbpm_fix")
sys.path.insert(0, "/home/sogang/jaehoon/VBPM_reintegration/vbpm_postmortem")
import pm_common as P                                                   # noqa: E402
import variant_b as VB                                                  # noqa: E402
from m2_targets import pf_targets                                       # noqa: E402
from vbpm.distributions import (TWO_PI, gumbel_softmax, kl_categorical,  # noqa: E402
                                kl_wrapped_cauchy)
from vbpm.evaluate import beats_from_barphase, f_measure                # noqa: E402

OUT = "/home/sogang/jaehoon/VBPM_reintegration/vbpm_innovq"
FPS = 50.0
RHO_P = math.exp(-P.PHYS["gamma_phase"])       # 0.99945015...
GP1 = 1.0 - RHO_P                              # 1 - rho_p, exact double
DOF = P.PHYS["t_dof"]                          # 2.0 (fixed physical; q uses the same)
T_SCALE = P.PHYS["t_scale"]                    # 0.00125
DEV_SIGMA = P.PHYS["dev_sigma"]                # 1e-3 (dev pinned: q == p, KL = 0)
INIT_LV_MU = P.PHYS["init_level_mu"]
INIT_LV_S = P.PHYS["init_level_scale"]


def softplus_inv(y):
    return math.log(math.expm1(y))


R0 = softplus_inv(GP1)                 # innov rho bias: zero head output -> rho_q = rho_p
B_SLT0 = softplus_inv(T_SCALE - 1e-5)  # innov s_lv bias: zero output -> s_lv = sigma_dlt
B_LS0 = softplus_inv(INIT_LV_S - 0.05)  # init level-scale bias: zero output -> 0.3


def wrap(x):
    return (x + math.pi) % TWO_PI - math.pi


def kl_phase_innov(mu_eps, sq):
    """Closed-form per-step innovation KL: KL(WC(mu_eps, 1-sq) || WC(0, rho_p)).

    Cancellation-free form (SPEC (b), 'numerically superior accountant'):
      num = d^2 + 4 rho_q rho_p sin^2(mu/2),  d = 1 - rho_q rho_p = sq + (1-sq)(1-rho_p)
      den = (1-rho_q^2)(1-rho_p^2) = sq (2-sq) (1-rho_p)(1+rho_p)
    computed in float64 with sq = 1-rho_q taken DIRECTLY from the softplus output
    (never as 1-rho after rounding). Exactly 0 at mu=0, sq=1-rho_p.
    """
    mu = mu_eps.double()
    s = sq.double().clamp(1e-9, 0.5)
    rq = 1.0 - s
    d = s + rq * GP1
    num = d * d + 4.0 * rq * RHO_P * torch.sin(mu / 2.0) ** 2
    den = s * (2.0 - s) * GP1 * (1.0 + RHO_P)
    return torch.log(num / den)


class InnovQ(VB.BarPointerVAE_B):
    """BarPointerVAE_B trunk + innovation-space posterior heads (SPEC (a))."""

    def __init__(self, s_phi=0.05, s_lt=0.0025, rho1_max=0.9, head_init_std=1e-3):
        super().__init__(h_dim=2, hidden=128, num_meters=4, obs_dim=2, obs_type="bern")
        self.s_phi = float(s_phi)          # mutable (anneal)
        self.s_lt = float(s_lt)
        self.rho1_max = float(rho1_max)
        hid = self.hidden
        # (i) t=1 head: [mean_t c_t, c_1] -> K meter logits | u,v | rho1_raw | lv_mu | lv_s_raw
        self.init_head = nn.Sequential(
            nn.Linear(2 * hid, hid), nn.Tanh(), nn.Linear(hid, self.K + 5))
        # (ii) innovation head: [c_t, z_feat(z_{t-1})] -> phi_raw | rho_raw | lt_raw | s_lv_raw
        self.innov_head = nn.Sequential(
            nn.Linear(hid + self.z_feat_dim, hid), nn.Tanh(), nn.Linear(hid, 4))
        with torch.no_grad():
            # small (not zero) final weights: near-neutral start, but gradient reaches
            # every layer from step 1 (smoke check iii).
            for lin in (self.init_head[-1], self.innov_head[-1]):
                lin.weight.normal_(0.0, head_init_std)
                lin.bias.zero_()
            self.init_head[-1].bias[self.K] = 1.0        # (u,v)=(1,0) -> mu_phi1 = 0
            self.init_head[-1].bias[self.K + 4] = B_LS0  # s_l1 init = 0.3 (prior init scale)
        Pi = torch.full((self.K, self.K), (1.0 - P.PHYS["meter_self"]) / (self.K - 1))
        Pi.fill_diagonal_(P.PHYS["meter_self"])
        self.register_buffer("Pi_phys", Pi)


def rollout(model, h, b, *, sample=True, temperature=0.3, zero_innov=False, u_eps=1e-4):
    """q's sampler = prior recursion + encoder nudges. Full BPTT (no detach).

    Returns Z [B,T,7], phi/lt trajectories, per-crop KLs (phase/level/meter; dev pinned
    -> 0 by construction), and detached diagnostics (MU, SQ, saturation).
    """
    Bn, T, _ = h.shape
    dev = h.device
    K = model.K
    dof_t = torch.tensor(DOF, device=dev)
    tsc = torch.full((Bn,), T_SCALE, device=dev)
    zero = torch.zeros(Bn, device=dev)

    ctx = model.encode_posterior(h, b)                                   # [B,T,hid]
    init = model.init_head(torch.cat([ctx.mean(1), ctx[:, 0]], -1))      # [B,K+5]
    m_logits = init[:, :K]
    mu_phi1 = torch.atan2(init[:, K + 1], init[:, K]) % TWO_PI
    rho1 = (torch.sigmoid(init[:, K + 2]) * model.rho1_max).clamp(1e-6, 1 - 1e-6)
    mu_l1 = init[:, K + 3] + model.level_offset
    s_l1 = F.softplus(init[:, K + 4]) + 0.05

    if sample:
        u1 = torch.rand(Bn, device=dev).clamp(u_eps, 1.0 - u_eps)
        phi = (mu_phi1 + (-torch.log(rho1)) * torch.tan(math.pi * (u1 - 0.5))) % TWO_PI
        level = torch.distributions.StudentT(dof_t, mu_l1, s_l1).rsample()
        dv = DEV_SIGMA * torch.randn(Bn, device=dev)
        meter = gumbel_softmax(m_logits, temperature)
    else:
        phi, level, dv = mu_phi1, mu_l1, zero
        meter = F.softmax(m_logits / max(temperature, 1e-6), -1)
    lt = level + dv

    # t=1 KLs vs the physical init (phase WC(pi,1e-6); level St-t; meter uniform; dev q==p)
    kl_p = kl_wrapped_cauchy(mu_phi1, rho1,
                             torch.full_like(mu_phi1, math.pi),
                             torch.full_like(mu_phi1, 1e-6)).double()
    kl_l = P.kl_t_mc(dof_t, mu_l1, s_l1, dof_t,
                     torch.full((Bn,), INIT_LV_MU, device=dev),
                     torch.full((Bn,), INIT_LV_S, device=dev), level)
    kl_m = kl_categorical(torch.log_softmax(m_logits, -1),
                          torch.full((Bn, K), -math.log(K), device=dev))
    n_cross = torch.ones(Bn, device=dev)

    z_feats = [model.z_features(meter, phi, lt)]
    phis, lts = [phi], [lt]
    MU, SQ = [], []
    for t in range(1, T):
        zf = model.z_features(meter, phi, lt)
        out = model.innov_head(torch.cat([ctx[:, t], zf], -1))
        mu_eps = torch.tanh(out[:, 0]) * model.s_phi
        sq = F.softplus(out[:, 1] + R0).clamp(1e-6, 0.5)      # = 1 - rho_q; ONE shared clamp feeds sampler AND KL (review M2)
        mu_lt = torch.tanh(out[:, 2]) * model.s_lt
        s_lv = F.softplus(out[:, 3] + B_SLT0) + 1e-5
        if zero_innov:
            mu_eps = mu_eps * 0.0
            mu_lt = mu_lt * 0.0

        tempo = torch.exp(lt.clamp(-12.0, 6.0))
        advance = phi + tempo
        cross = (advance >= TWO_PI).to(h.dtype)

        if sample:
            u = torch.rand(Bn, device=dev).clamp(u_eps, 1.0 - u_eps)
            gam_q = -torch.log1p(-sq)         # = -log(1-sq) = -log rho_q  (blind-T2 fix: was -log(sq) ~ 7.5 -> uniform phase)
            eps = mu_eps + gam_q * torch.tan(math.pi * (u - 0.5))
            eps_lt = torch.distributions.StudentT(dof_t, mu_lt, s_lv).rsample()
            dv = DEV_SIGMA * torch.randn(Bn, device=dev)
            m_draw = gumbel_softmax(m_logits, temperature)
        else:
            eps, eps_lt, dv = mu_eps, mu_lt, zero
            m_draw = F.softmax(m_logits / max(temperature, 1e-6), -1)

        meter_prev = meter
        phi = (advance + eps) % TWO_PI
        level = level + eps_lt
        lt = level + dv
        meter = torch.where(cross.unsqueeze(-1) > 0.5, m_draw, meter_prev)

        kl_p = kl_p + kl_phase_innov(mu_eps, sq)              # sample-path independent
        kl_l = kl_l + P.kl_t_mc(dof_t, mu_lt, s_lv, dof_t, zero, tsc, eps_lt)
        kl_m = kl_m + cross * kl_categorical(
            torch.log_softmax(m_logits, -1),
            torch.log(meter_prev @ model.Pi_phys + 1e-9))
        n_cross = n_cross + cross

        z_feats.append(model.z_features(meter, phi, lt))
        phis.append(phi); lts.append(lt)
        MU.append(mu_eps.detach()); SQ.append(sq.detach())

    MU = torch.stack(MU, 1); SQ = torch.stack(SQ, 1)          # [B,T-1] detached
    return dict(Z=torch.stack(z_feats, 1),
                phi=torch.stack(phis, 1), lt=torch.stack(lts, 1),
                kl_p=kl_p.float(), kl_l=kl_l, kl_m=kl_m,
                kl_dv=torch.zeros(Bn, device=dev),            # dev pinned: q == p
                n_cross=n_cross, MU=MU, SQ=SQ,
                init_vec=init, ctx=ctx,
                mu_phi1=mu_phi1.detach(), rho1=rho1.detach(),
                mu_l1=mu_l1.detach(), s_l1=s_l1.detach(),
                mean_abs_innov=float(MU.abs().mean()))


def _diag_fill(ro, model):
    ro["sat_frac"] = float((ro["MU"].abs() > 0.8 * model.s_phi).float().mean())
    ro["rho_q_mean"] = float((1.0 - ro["SQ"]).mean())
    ro["max_sq"] = float(ro["SQ"].max())
    return ro


# swappable rollout: set by --fast to the parallel-in-time implementation.
# rollout_vec_s: NOT exact for sampled T=1500 -- ~1/24 crops differ by one bar-crossing
# (dkl_m 0.97 nats); the 1.7e-4 gate number was measured on ONE small batch and does not
# hold at the training configuration. Acceptable vs ELBO sampling variance, but --fast runs
# must not be pooled with non-fast runs. See rollout_vec_s.py KNOWN LIMITATION.
# (superseded gate note:
# KLs to 2e-5 nats, gradient cosine 1.000000, 451x) and REQUIRES n_picard>=8 when
# sampling -- at 4 the kl_p error is 7e-2 nats.
ROLLOUT_FN = None

def _rollout(model, h, b, **kw):
    if ROLLOUT_FN is None or kw.get("zero_innov"):
        return rollout(model, h, b, **kw)
    kw.pop("u_eps", None); kw.pop("zero_innov", None)
    return ROLLOUT_FN(model, h, b, n_picard=8, **kw)


def elbo_innovq(model, D, dec, hdec, *, idx=None, beta=1.0, sample=True,
                temperature=0.3, obs_w=1.0, recon="bce", zero_innov=False):
    h, b, db, obs = D["h"], D["b"], D["db"], D["obs"]
    if idx is not None:
        h, b, db, obs = h[idx], b[idx], db[idx], obs[idx]
    ro = _rollout(model, h, b, sample=sample, temperature=temperature, zero_innov=zero_innov)
    _diag_fill(ro, model)
    rb, rd, roo = P.recon_terms(dec, hdec, ro["Z"], b, db, obs, recon=recon)
    L_kl = ro["kl_p"] + ro["kl_l"] + ro["kl_m"] + ro["kl_dv"]
    loss = (rb + rd + obs_w * roo + beta * L_kl).mean()
    info = dict(loss=float(loss), recon_beat=float(rb.mean()), recon_db=float(rd.mean()),
                recon_obs=float(roo.mean()), kl=float(L_kl.mean()),
                kl_phase=float(ro["kl_p"].mean()), kl_level=float(ro["kl_l"].mean()),
                kl_meter=float(ro["kl_m"].mean()), kl_dev=0.0,
                n_cross=float(ro["n_cross"].mean()),
                mean_abs_innov=float(ro["MU"].abs().mean()),
                sat_frac=ro["sat_frac"], rho_q=ro["rho_q_mean"], max_sq=ro["max_sq"],
                rho1=float(ro["rho1"].mean()), s_phi=model.s_phi)
    return loss, info, ro


@torch.no_grad()
def probe(model, D, dec, hdec, TEA=None, chunk=48, recon="bce", temperature=0.3):
    """Mean-rollout probe (sample=False): corr-to-truth, corr-to-teacher, TF-F, KL
    breakdown, innovation diagnostics. Mirrors m2_distill.probe conventions."""
    model.eval()
    Bn = D["h"].shape[0]
    phis, kls = [], dict(kl_phase=[], kl_level=[], kl_meter=[], rb=[], rd=[], ro=[])
    mu_abs, sat, rhoq = [], [], []
    msq = 0.0
    for i in range(0, Bn, chunk):
        idx = torch.arange(i, min(i + chunk, Bn), device=D["h"].device)
        _, info, ro = elbo_innovq(model, D, dec, hdec, idx=idx, beta=1.0, sample=False,
                                  temperature=temperature, recon=recon)
        phis.append(ro["phi"])
        kls["kl_phase"].append(ro["kl_p"]); kls["kl_level"].append(ro["kl_l"])
        kls["kl_meter"].append(ro["kl_m"])
        mu_abs.append(ro["MU"].abs().flatten()); sat.append(
            (ro["MU"].abs() > 0.8 * model.s_phi).float().flatten())
        rhoq.append((1.0 - ro["SQ"]).flatten())
        msq = max(msq, float(ro["SQ"].max()))
    phi = torch.cat(phis, 0)
    dl = torch.exp(1j * (phi - D["phi"]))
    corr = float(torch.abs(dl.mean()))                       # POOLED resultant (m2 convention)
    corr_pc = float(torch.abs(dl.mean(dim=1)).mean())        # PER-CROP resultant (SPEC bracket convention)
    if TEA is not None:
        dt = torch.exp(1j * (phi - TEA["phi"]))
        ct = float(torch.abs(dt.mean()))
        ct_pc = float(torch.abs(dt.mean(dim=1)).mean())
    else:
        ct = ct_pc = float("nan")
    Fs, Fc = [], []
    for i in range(Bn):
        ref = np.where(D["b"][i].cpu().numpy() > 0.5)[0] / FPS
        if len(ref) < 4:
            continue
        ph = phi[i].cpu().numpy(); mi = int(D["m"][i])
        Fs.append(f_measure(ref, beats_from_barphase(ph, mi, FPS)))       # m2 convention
        Fc.append(f_measure(ref, beats_from_barphase(ph, mi + 1, FPS)))   # corrected bpb
    model.train()
    return dict(tf_F=float(np.mean(Fs)), tf_F_corr=float(np.mean(Fc)), corr=corr,
                corr_percrop=corr_pc, corr_teacher=ct, corr_teacher_percrop=ct_pc,
                max_sq=msq,
                kl_phase=float(torch.cat(kls["kl_phase"]).mean()),
                kl_level=float(torch.cat(kls["kl_level"]).mean()),
                kl_meter=float(torch.cat(kls["kl_meter"]).mean()),
                mean_abs_innov=float(torch.cat(mu_abs).mean()),
                sat_frac=float(torch.cat(sat).mean()),
                rho_q=float(torch.cat(rhoq).mean()))


def placement_loss(model, D, TEA, idx, temperature=0.3, w_roll=1.0):
    """Placement v2 (blind-T3 fix). Three terms, phi/lt supervision only (m2 latents):
      (1) L_roll: m2's free-rollout trajectory loss (unchanged) -- BPTT credit assignment;
      (2) L_init: DIRECT anchor of the t=1 head to the teacher's absolute offset
          (supervise raw (u,v) toward (cos,sin) of tea_phi[:,0], level mu to tea_lt[:,0])
          -- blind T3 showed absolute offsets never align through L_roll alone
          (pooled corr 0.044) and innovations balloon 35x instead (kl_phase 1157);
      (3) L_tf: teacher-forced per-frame innovation matching -- the innov head is driven
          with the TEACHER state z_{t-1} and its mu_eps/mu_lt are regressed on the
          teacher's own innovations eps* = wrap(dphi - exp(lt_{t-1})), dlt*; normalized
          by the bounds so the loss is order-1.  All three end before handover."""
    h, b = D["h"][idx], D["b"][idx]
    tp, tl = TEA["phi"][idx], TEA["lt"][idx]
    if w_roll > 0.0:
        ro = _rollout(model, h, b, sample=False, temperature=temperature)
        L_roll = (1 - torch.cos(ro["phi"] - tp)).mean() * 10 \
            + ((ro["lt"] - tl) ** 2).mean()
        ctx = ro["ctx"]
    else:
        L_roll = torch.zeros((), device=h.device)
        ctx = model.encode_posterior(h, b)
    K = model.K
    # DENSE init supervision (v2.2): the single-point [mean,ctx0] regression is
    # unlearnable (400-step pilot: resultant plateau 0.10); the SAME head supervised at
    # every frame (m2-dense) reaches frame-0 resultant-vs-truth 0.486 by s300. The
    # rollout still consumes only the frame-0 application of this head.
    T = ctx.shape[1]
    inp = torch.cat([ctx.mean(1, keepdim=True).expand(-1, T, -1), ctx], -1)
    init_all = model.init_head(inp)                                  # [B,T,K+5]
    L_init = ((init_all[..., K] - torch.cos(tp)) ** 2
              + (init_all[..., K + 1] - torch.sin(tp)) ** 2).mean() \
        + ((init_all[..., K + 3] + model.level_offset - tl) ** 2).mean()
    init = init_all[:, 0]
    meter = F.softmax(init[:, :K] / max(temperature, 1e-6), -1)
    Tm1 = tp.shape[1] - 1
    zf = model.z_features(meter.unsqueeze(1).expand(-1, Tm1, -1), tp[:, :-1], tl[:, :-1])
    out = model.innov_head(torch.cat([ctx[:, 1:], zf], -1))
    b_phi, b_lt = 0.95 * model.s_phi, 0.95 * model.s_lt
    eps_star = wrap(tp[:, 1:] - tp[:, :-1]
                    - torch.exp(tl[:, :-1].clamp(-12.0, 6.0))).clamp(-b_phi, b_phi)
    dlt_star = (tl[:, 1:] - tl[:, :-1]).clamp(-b_lt, b_lt)
    mu_eps = torch.tanh(out[..., 0]) * model.s_phi
    mu_lt = torch.tanh(out[..., 2]) * model.s_lt
    L_tf = (((mu_eps - eps_star) / model.s_phi) ** 2).mean() \
        + (((mu_lt - dlt_star) / model.s_lt) ** 2).mean()
    return w_roll * L_roll + L_init + L_tf, dict(L_roll=float(L_roll),
                                                 L_init=float(L_init), L_tf=float(L_tf),
                                                 w_roll=float(w_roll))


def smooth_track(phi, win):
    """Placement-free smoothing of a phase track (copied verbatim from toy_kl_verify),
    v2.1: the lt track gets a SECOND boxcar (same win) so teacher tempo increments are
    representable by the bounded innovation head (dlt* out-of-bound 65% -> 17%); the
    teacher PHASE is untouched and remains exactly reproducible from (lt_smooth, eps*)
    [measured max reconstruction err 4.8e-6 rad; corr-to-truth unchanged 0.633533]."""
    d = wrap(phi[:, 1:] - phi[:, :-1])
    k = torch.ones(1, 1, win, device=phi.device) / win
    ds = F.conv1d(F.pad(d.unsqueeze(1), (win // 2, win // 2), mode="replicate"), k).squeeze(1)
    out = torch.cat([phi[:, :1], phi[:, :1] + torch.cumsum(ds, 1)], 1)
    lt = torch.log(ds.clamp(1e-4, 1.0))
    lt = torch.cat([lt[:, :1], lt], 1)[:, :phi.shape[1]]
    lt = F.conv1d(F.pad(lt.unsqueeze(1), (win // 2, win // 2), mode="replicate"), k).squeeze(1)
    return out % TWO_PI, lt


class Cut(nn.Module):
    """Cut log-tempo from the decoder input (m2 convention)."""
    def __init__(self, m):
        super().__init__()
        self.m = m

    def forward(self, z):
        return self.m(torch.cat([z[..., :2], torch.zeros_like(z[..., 2:3]), z[..., 3:]], -1))


# ======================================================================================
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--placement", default="pf_sm101",
                    choices=["pf_sm101", "pf_sm51", "pf_raw", "label", "cold"])
    ap.add_argument("--pre", type=int, default=600)        # placement steps (beta=0)
    ap.add_argument("--steps", type=int, default=800)      # ELBO steps
    ap.add_argument("--every", type=int, default=50)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--tag", default=None)
    ap.add_argument("--beta_max", type=float, default=1.0)
    ap.add_argument("--beta_ramp", type=int, default=100)
    ap.add_argument("--s_phi", type=float, default=0.05)
    ap.add_argument("--s_phi_end", type=float, default=None)   # anneal target (None = off)
    ap.add_argument("--anneal_start", type=int, default=200)   # ELBO step anneal begins
    ap.add_argument("--anneal_steps", type=int, default=300)
    ap.add_argument("--s_lt", type=float, default=0.0025)      # = 2*sigma_dlt
    ap.add_argument("--rho1_max", type=float, default=0.9)
    ap.add_argument("--head_init_std", type=float, default=1e-3)
    ap.add_argument("--lr_pre", type=float, default=1e-3)
    ap.add_argument("--lr", type=float, default=3e-4)
    ap.add_argument("--temp", type=float, default=0.3)
    ap.add_argument("--obs_w", type=float, default=1.0)
    ap.add_argument("--recon", default="bce", choices=["bce", "stmask", "stpool", "cramer", "hybrid"])
    ap.add_argument("--crop", type=int, default=1500)
    ap.add_argument("--fast", action="store_true")
    ap.add_argument("--no_abort", action="store_true")
    ap.add_argument("--tg", action="store_true")
    ap.add_argument("--gamma_phase", type=float, default=None)  # wrapped-Cauchy innovation prior scale
    ap.add_argument("--dec_freeze", action="store_true")  # keep the pretrained read-out fixed
    ap.add_argument("--tg_freeze", action="store_true")  # hold the level head after tg_pre
    ap.add_argument("--tg_pre", type=int, default=0)  # supervised init of the tempogram level head
    ap.add_argument("--dec_pre", type=int, default=0)   # fit decoders on ORACLE phase first
    ap.add_argument("--cram_anneal", type=int, default=0)  # steps to anneal CRAMER_LAM -> 0   # tempogram-fed init head (level from ACF, not mean-pool)  # criterion is calibrated to the warm-start regime   # parallel-in-time rollout (451x)   # 30s: TRUTH beats COAST by 46 nats here
    ap.add_argument("--smoke", action="store_true")
    A = ap.parse_args()
    TAG = A.tag or (("smoke_" if A.smoke else "") + f"{A.placement}_s{A.seed}")
    dev = "cuda:0"
    if A.gamma_phase is not None:
        # 5.5e-4 rad/frame prices phase correction out of existence: mu=5e-4 costs 282
        # nats/crop while the ENTIRE recon benefit of correct phase is ~117 nats.
        # Physical microtiming ~15ms @ 24 frames/beat is ~0.049 rad.
        # GP1 and R0 are DERIVED from RHO_P at import; rebinding RHO_P alone left
        # kl_phase_innov mixing a new RHO_P with a stale GP1 (93x understated KL) and
        # left R0 initialising rho_q at the OLD prior. Rebind all three together.
        global RHO_P, GP1, R0
        P.PHYS["gamma_phase"] = A.gamma_phase
        RHO_P = math.exp(-A.gamma_phase)
        GP1 = 1.0 - RHO_P
        R0 = softplus_inv(GP1)
        print(f"[prior] gamma_phase={A.gamma_phase:.4g} -> RHO_P={RHO_P:.6f} "
              f"GP1={GP1:.6e} R0={R0:.4f}", flush=True)
    if A.fast:
        global ROLLOUT_FN
        from rollout_vec_s import rollout_vec_s as _rvs
        ROLLOUT_FN = _rvs
        print("[fast] parallel-in-time rollout enabled (picard=8)", flush=True)
    torch.manual_seed(A.seed)
    rng = np.random.default_rng(A.seed)

    train = P.build_crops(P.load_songs("train"), n_per_song=2, seed=0, crop=A.crop, dev=dev)
    ev = P.build_crops(P.load_songs("eval"), n_per_song=1, seed=1, crop=A.crop, dev=dev)
    Ntr, T = train["b"].shape

    TEA = None
    if A.placement == "label":
        TEA = dict(phi=train["phi"], lt=train["lt"])
    elif A.placement != "cold":
        PF = pf_targets("train", 2, 0, A.crop, lt_src="phase", dev=dev)
        if A.placement == "pf_raw":
            TEA = dict(phi=PF["phi"], lt=PF["lt"])
        else:
            w = int(A.placement.replace("pf_sm", ""))
            sphi, slt = smooth_track(PF["phi"], w)
            TEA = dict(phi=sphi, lt=slt)
    if TEA is not None:
        dtc = torch.exp(1j * (TEA["phi"] - train["phi"]))
        tea_corr = float(torch.abs(dtc.mean()))                    # pooled (m2 logs)
        tea_corr_pc = float(torch.abs(dtc.mean(dim=1)).mean())     # per-crop (SPEC bracket)
    else:
        tea_corr = tea_corr_pc = float("nan")

    _CLS = InnovQ
    if A.tg:
        from innovq_tg import InnovQT as _CLS
        print("[tg] tempogram-fed init head enabled", flush=True)
    model = _CLS(s_phi=A.s_phi, s_lt=A.s_lt, rho1_max=A.rho1_max,
                 head_init_std=A.head_init_std).to(dev)
    d0, h0 = P.new_decoders(dev)
    dec, hdec = Cut(d0), Cut(h0)
    ALLP = lambda: list(model.parameters()) + list(d0.parameters()) + list(h0.parameters())
    if A.tg_pre > 0:
        # corr is ~entirely a function of TEMPO error (isolation: true-tempo 0.998 vs
        # model-tempo 0.270). The ELBO's tempo signal is ~1% of the loss level, below the
        # sampling noise floor, so the level head cannot learn it by descent. Initialize it
        # the way the read-out is initialized -- then ELBO-train. Objective is unchanged.
        _lvl = torch.log(2 * math.pi / (4.0 * torch.stack([
            torch.median(torch.diff(torch.nonzero(train["b"][i] > 0.5).squeeze(-1)).float())
            if (train["b"][i] > 0.5).sum() >= 8 else torch.tensor(float("nan"), device=dev)
            for i in range(Ntr)])))
        _ok = torch.nonzero(~torch.isnan(_lvl)).squeeze(-1)
        _op = torch.optim.AdamW([q for q in model.parameters() if q.requires_grad], lr=1e-3)
        for _s in range(A.tg_pre):
            _op.zero_grad()
            _sel = _ok[torch.randperm(len(_ok), device=dev)[:24]]
            _c = model.encode_posterior(train["h"][_sel], train["b"][_sel])
            _mu = model.init_head(torch.cat([_c.mean(1), _c[:, 0]], -1))[:, model.K + 3] + model.level_offset
            (_mu - _lvl[_sel]).abs().mean().backward(); _op.step()
        with torch.no_grad():
            _c = model.encode_posterior(train["h"][_ok[:200]], train["b"][_ok[:200]])
            _mu = model.init_head(torch.cat([_c.mean(1), _c[:, 0]], -1))[:, model.K + 3] + model.level_offset
            _m = float((_mu - _lvl[_ok[:200]]).abs().mean())
        print(f"[tg_pre] level head initialized, train MAE {100*_m:.2f}% (2% needed for corr>=0.82)", flush=True)
        if A.tg_freeze:
            # MEASURED: the ELBO drives log-tempo AWAY from truth (10.8% -> 37% in 75 steps,
            # worse than predicting the corpus mean). Hold the level head so corr can be
            # attributed to phase tracking rather than tempo drift.
            for _q in list(model.init_head.parameters()) + list(model.tg_embed.parameters()
                          if hasattr(model, "tg_embed") else []):
                _q.requires_grad_(False)
            print("[tg_freeze] level/init head FROZEN", flush=True)

    if A.dec_pre > 0:
        # At init the recon is phase-BLIND (+0.00% to a full phase scramble), so the
        # decoder's cheapest descent is the marginal beat density -- after which the
        # latent can never earn gradient back. Fit the read-out on the oracle trajectory
        # first so phase carries signal from ELBO step 1.
        _mi = train["m"].long().clamp(0, model.K - 1)
        mo = F.one_hot(_mi, model.K).float()
        if mo.dim() == 2:
            mo = mo.unsqueeze(1).expand(-1, T, -1)
        Zor = torch.cat([torch.cos(train["phi"]).unsqueeze(-1), torch.sin(train["phi"]).unsqueeze(-1),
                         train["lt"].unsqueeze(-1), mo], -1)
        od = torch.optim.Adam(list(d0.parameters()) + list(h0.parameters()), lr=3e-3)
        for _s in range(A.dec_pre):
            od.zero_grad()
            sel = torch.randperm(Ntr, device=dev)[:16]
            rb_, rd_, ro_ = P.recon_terms(dec, hdec, Zor[sel], train["b"][sel], train["db"][sel],
                                          train["obs"][sel], recon=A.recon)
            (rb_ + rd_ + ro_).mean().backward(); od.step()
        print(f"[dec_pre] fit read-out on oracle phase for {A.dec_pre} steps", flush=True)
        # sensitivity check: recon must RISE when phase is scrambled, else the pretrain failed
        with torch.no_grad():
            _p2 = (train["phi"][:16] + 0.05 * torch.arange(T, device=dev).float()) % TWO_PI
            _Z2 = torch.cat([torch.cos(_p2).unsqueeze(-1), torch.sin(_p2).unsqueeze(-1),
                             train["lt"][:16].unsqueeze(-1), mo[:16]], -1)
            _a = P.recon_terms(dec, hdec, Zor[:16], train["b"][:16], train["db"][:16],
                               train["obs"][:16], recon=A.recon)
            _b = P.recon_terms(dec, hdec, _Z2, train["b"][:16], train["db"][:16],
                               train["obs"][:16], recon=A.recon)
            _r0 = float((_a[0] + _a[1]).mean()); _r1 = float((_b[0] + _b[1]).mean())
        print(f"[dec_pre] phase sensitivity: {_r0:.1f} -> {_r1:.1f} ({100*(_r1-_r0)/abs(_r0):+.2f}%)", flush=True)
        if A.dec_freeze:
            for _p in list(d0.parameters()) + list(h0.parameters()):
                _p.requires_grad_(False)
            ALLP = lambda: [q for q in model.parameters() if q.requires_grad]
            print("[dec_freeze] read-out FROZEN: latent is the only route to lower recon", flush=True)
    print(f"[{TAG}] train {Ntr}x{T} | eval {ev['b'].shape[0]}x1000 | "
          f"corr(teacher,truth) pooled={tea_corr:.4f} percrop={tea_corr_pc:.4f} | "
          f"rho_p={RHO_P:.6f} s_phi={model.s_phi} "
          f"s_lt={model.s_lt} rho1_max={model.rho1_max}", flush=True)

    # ---------------- SMOKE ----------------
    if A.smoke:
        smoke = dict(tag=TAG, seed=A.seed)
        h3, b3 = train["h"][:3], train["b"][:3]
        # (i) zero innovations -> EXACT prior-mean recursion
        with torch.no_grad():
            ro = rollout(model, h3, b3, sample=False, zero_innov=True)
            phi, lt = ro["phi"], ro["lt"]
            cur = phi[:, 0].clone()
            dmax = 0.0
            for t in range(1, T):
                cur = (cur + torch.exp(lt[:, t - 1].clamp(-12.0, 6.0))) % TWO_PI
                dmax = max(dmax, float(wrap(phi[:, t] - cur).abs().max()))
            smoke["i_max_abs_recursion_diff_rad"] = dmax
            smoke["i_lt_drift"] = float((lt[:, -1] - lt[:, 0]).abs().max())
        # (ii) kl_phase at zero-mean innovations vs independent float64 analytic
        with torch.no_grad():
            kl_code = float(ro["kl_p"].mean())
            mu = ro["MU"].double().cpu().numpy()
            rq = (1.0 - ro["SQ"].double()).cpu().numpy()
            num = 1.0 - 2.0 * rq * RHO_P * np.cos(mu) + (rq * RHO_P) ** 2
            den = (1.0 - rq ** 2) * (1.0 - RHO_P ** 2)
            per_step = np.log(num / den).sum(1)
            r1 = ro["rho1"].double().cpu().numpy()
            m1 = ro["mu_phi1"].double().cpu().numpy()
            rp1 = 1e-6
            t1 = np.log((1 - 2 * r1 * rp1 * np.cos(m1 - math.pi) + (r1 * rp1) ** 2)
                        / ((1 - r1 ** 2) * (1 - rp1 ** 2)))
            kl_ana = float((per_step + t1).mean())
            smoke["ii_kl_phase_code"] = kl_code
            smoke["ii_kl_phase_analytic64"] = kl_ana
            smoke["ii_ratio"] = kl_code / kl_ana if kl_ana != 0 else float("inf")
        # (iii) gradients reach innovation + t=1 heads
        model.zero_grad(set_to_none=True)
        idx3 = torch.arange(3, device=dev)
        loss, info0, _ = elbo_innovq(model, train, dec, hdec, idx=idx3, beta=1.0,
                                     sample=True, temperature=A.temp, obs_w=A.obs_w,
                                     recon=A.recon)
        loss.backward()
        g = {}
        for name in ["innov_head.0.weight", "innov_head.2.weight", "innov_head.2.bias",
                     "init_head.0.weight", "init_head.2.weight", "init_head.2.bias",
                     "post_gru.weight_ih_l0", "post_ctx.weight"]:
            p = dict(model.named_parameters())[name]
            g[name] = dict(norm=float(p.grad.norm()) if p.grad is not None else None,
                           finite=bool(torch.isfinite(p.grad).all()) if p.grad is not None
                           else False)
        smoke["iii_grads"] = g
        smoke["iii_elbo_info_3crop"] = info0
        model.zero_grad(set_to_none=True)
        # 50 steps must run without NaN: 25 placement + 25 ELBO (ramp 10)
        nan_free = True
        losses_pre, losses_elbo = [], []
        if TEA is not None:
            opt = torch.optim.AdamW(model.parameters(), lr=A.lr_pre)
            for s in range(25):
                idx = torch.tensor(rng.integers(0, Ntr, A.batch), device=dev,
                                   dtype=torch.long)
                l, _pl = placement_loss(model, train, TEA, idx, temperature=A.temp,
                                        w_roll=1.0 if s >= 15 else 0.0)
                opt.zero_grad(); l.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0); opt.step()
                losses_pre.append(float(l))
                nan_free &= math.isfinite(float(l))
        opt = torch.optim.AdamW(ALLP(), lr=A.lr)
        for s in range(1, 26):
            beta = A.beta_max * min(1.0, s / 10)
            idx = torch.tensor(rng.integers(0, Ntr, A.batch), device=dev, dtype=torch.long)
            loss, info, _ = elbo_innovq(model, train, dec, hdec, idx=idx, beta=beta,
                                        sample=True, temperature=A.temp, obs_w=A.obs_w,
                                        recon=A.recon)
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(ALLP(), 5.0); opt.step()
            losses_elbo.append(float(loss))
            nan_free &= math.isfinite(float(loss))
            nan_free &= all(math.isfinite(v) for v in
                            (info["kl_phase"], info["kl_level"], info["kl_meter"]))
        smoke["pre_losses"] = losses_pre
        smoke["elbo_losses"] = losses_elbo
        smoke["elbo_info_last"] = info
        smoke["nan_free_50_steps"] = bool(nan_free)
        pr = probe(model, ev, dec, hdec, recon=A.recon, temperature=A.temp)
        smoke["probe_eval_after50"] = pr
        json.dump(smoke, open(f"{OUT}/smoke_{TAG}.json", "w"), indent=1, default=float)
        print(json.dumps({k: v for k, v in smoke.items()
                          if k not in ("pre_losses", "elbo_losses")}, indent=1,
                         default=float), flush=True)
        print(f"[{TAG}] SMOKE {'PASS' if nan_free else 'FAIL'} -> {OUT}/smoke_{TAG}.json",
              flush=True)
        return

    # ---------------- FULL RUN (m2 protocol) ----------------
    hist = []
    def snapshot(stage, step, extra):
        row = dict(stage=stage, step=step, **extra)
        hist.append(row)
        json.dump(dict(args=vars(A), teacher_corr=tea_corr, teacher_corr_percrop=tea_corr_pc,
                       corr_convention_note="bracket 0.60-0.635 & abort<0.50 are PER-CROP "
                       "resultant (SPEC/toy_kl_verify convention); 'corr' key is POOLED (m2)",
                       hist=hist),
                  open(f"{OUT}/innovq_{TAG}.json", "w"), indent=1, default=float)
        return row

    t0 = time.time()
    if TEA is not None and A.pre > 0:
        opt = torch.optim.AdamW(model.parameters(), lr=A.lr_pre)
        for s in range(1, A.pre + 1):
            idx = torch.tensor(rng.integers(0, Ntr, A.batch), device=dev, dtype=torch.long)
            wr = max(0.0, min(1.0, (s - A.pre / 2) / max(A.pre / 4, 1)))
            loss, pl_terms = placement_loss(model, train, TEA, idx, temperature=A.temp,
                                            w_roll=wr)
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0); opt.step()
            if s % A.every == 0 or s == 1:
                pe = probe(model, ev, dec, hdec, recon=A.recon, temperature=A.temp)
                pt = probe(model, train, dec, hdec, TEA=TEA, recon=A.recon,
                           temperature=A.temp)
                snapshot("pre", s, dict(loss=float(loss), pl=pl_terms, ev=pe, tr=pt))
                print(f"[{TAG}][PRE ] s{s:4d} sup={float(loss):8.4f} "
                      f"(roll={pl_terms['L_roll']:.3f}*{pl_terms['w_roll']:.2f} "
                      f"init={pl_terms['L_init']:.3f} "
                      f"tf={pl_terms['L_tf']:.3f}) | ev F={pe['tf_F']:.3f}"
                      f" Fc={pe['tf_F_corr']:.3f} corr={pe['corr']:+.4f} | "
                      f"tr corr={pt['corr']:+.4f}/pc={pt['corr_percrop']:+.4f} "
                      f"c2t={pt['corr_teacher']:+.4f}/pc={pt['corr_teacher_percrop']:+.4f} "
                      f"klph={pt['kl_phase']:.1f} |mu|={pt['mean_abs_innov']:.5f} "
                      f"sat={pt['sat_frac']:.3f} | {s/(time.time()-t0):.2f} it/s", flush=True)

    pe = probe(model, ev, dec, hdec, recon=A.recon, temperature=A.temp)
    pt = probe(model, train, dec, hdec, TEA=TEA, recon=A.recon, temperature=A.temp)
    snapshot("handover", 0, dict(ev=pe, tr=pt))
    print(f"[{TAG}] HANDOVER ev F={pe['tf_F']:.3f} corr={pe['corr']:+.4f} | "
          f"tr corr={pt['corr']:+.4f} klph={pt['kl_phase']:.1f}", flush=True)

    opt = torch.optim.AdamW(ALLP(), lr=A.lr)
    t1 = time.time()
    # Pre-registered abort (restated in the NAMED per-crop-resultant convention, review M1:
    # the SPEC bracket 0.60-0.635 and the SVI grounding 0.634->0.635 are per-crop numbers;
    # the pooled m2 convention is logged alongside). Two consecutive probes = 100 steps.
    abort_hits = 0
    for s in range(1, A.steps + 1):
        beta = A.beta_max * min(1.0, s / A.beta_ramp)
        if A.s_phi_end is not None and s > A.anneal_start:
            frac = min(1.0, (s - A.anneal_start) / max(A.anneal_steps, 1))
            model.s_phi = A.s_phi + frac * (A.s_phi_end - A.s_phi)
        idx = torch.tensor(rng.integers(0, Ntr, A.batch), device=dev, dtype=torch.long)
        loss, info, _ = elbo_innovq(model, train, dec, hdec, idx=idx, beta=beta,
                                    sample=True, temperature=A.temp, obs_w=A.obs_w,
                                    recon=A.recon)
        opt.zero_grad(); loss.backward()
        torch.nn.utils.clip_grad_norm_(ALLP(), 5.0); opt.step()
        if s % A.every == 0 or s == 1:
            pe = probe(model, ev, dec, hdec, recon=A.recon, temperature=A.temp)
            pt = probe(model, train, dec, hdec, TEA=TEA, recon=A.recon, temperature=A.temp)
            snapshot("elbo", s, dict(beta=beta, loss=float(loss), s_phi=model.s_phi,
                                     batch_info=info, ev=pe, tr=pt))
            print(f"[{TAG}][ELBO] s{s:4d} b={beta:.2f} L={float(loss):9.1f} | "
                  f"ev F={pe['tf_F']:.3f} Fc={pe['tf_F_corr']:.3f} corr={pe['corr']:+.4f} | "
                  f"tr corr={pt['corr']:+.4f}/pc={pt['corr_percrop']:+.4f} "
                  f"c2t={pt['corr_teacher']:+.4f} "
                  f"klph={pt['kl_phase']:.1f} kll={pt['kl_level']:.1f} "
                  f"|mu|={pt['mean_abs_innov']:.5f} sat={pt['sat_frac']:.3f} "
                  f"rho_q={pt['rho_q']:.5f} msq={pt['max_sq']:.4f} | "
                  f"{s/(time.time()-t1):.2f} it/s", flush=True)
            if s >= A.beta_ramp:
                bad = (pt["corr_percrop"] < 0.50 or pt["kl_phase"] > 1000.0
                       or pt["sat_frac"] > 0.30)
                abort_hits = abort_hits + 1 if bad else 0
                if abort_hits >= 2 and not A.no_abort:
                    snapshot("abort", s, dict(reason=dict(
                        corr_percrop=pt["corr_percrop"], kl_phase=pt["kl_phase"],
                        sat_frac=pt["sat_frac"]), ev=pe, tr=pt))
                    torch.save(dict(model=model.state_dict(), dec=d0.state_dict(),
                                    hdec=h0.state_dict(), step=s, args=vars(A)),
                               f"{OUT}/innovq_{TAG}.pt")
                    print(f"[{TAG}] ABORT at s{s} (pre-registered criterion, per-crop "
                          f"convention)", flush=True)
                    return
        if s % 200 == 0:
            torch.save(dict(model=model.state_dict(), dec=d0.state_dict(),
                            hdec=h0.state_dict(), step=s, args=vars(A)),
                       f"{OUT}/innovq_{TAG}.pt")

    pe = probe(model, ev, dec, hdec, recon=A.recon, temperature=A.temp)
    pt = probe(model, train, dec, hdec, TEA=TEA, recon=A.recon, temperature=A.temp)
    fin = dict(tag=TAG, ev=pe, tr=pt, teacher_corr=tea_corr, teacher_corr_percrop=tea_corr_pc)
    snapshot("final", A.steps, fin)
    torch.save(dict(model=model.state_dict(), dec=d0.state_dict(), hdec=h0.state_dict(),
                    step=A.steps, args=vars(A), final=fin), f"{OUT}/innovq_{TAG}.pt")
    print(f"[{TAG}] FINAL {json.dumps(fin, default=float)}", flush=True)


if __name__ == "__main__":
    main()
